title: 和风天气图标
baseURL: "https://icons.qweather.com/"
defaultContentLanguage: zh
hasCJKLanguage: true
timeZone: Asia/Shanghai
enableRobotsTXT: false
enableGitInfo: true
disableKinds: ["taxonomy", "term", "RSS"]
markup:
  highlight:
    noClasses: false
  goldmark:
    renderer:
      unsafe: true

params:
  description: "开源、漂亮的天气图标库，支持SVG和Web Font，兼容和风天气API，适用于任何需要天气图标的项目。"
  logo: "https://cdn.qweather.com/media/qw-logo-s-dark-800.png"
  images: /assets/images/qweather-icons-hero.jpg
  copyright: "QWeather"
  mit: "https://github.com/qwd/Icons/blob/main/LICENSE"
  cc: "https://creativecommons.org/licenses/by/4.0/deed.zh"
  ver: "1.6.0"
  qw: "https://www.qweather.com"
  dev: "https://dev.qweather.com"
  map: "https://map.qweather.com"
  blog: "https://blog.qweather.com"
  github: "https://github.com/qwd"
  repo: "https://github.com/qwd/Icons"
  figma: "https://www.figma.com/community/file/1196353857920331062"
  app: "https://www.qweather.com/app/"
  icp:
    number: "京ICP备15048401号-11"
    link: "https://beian.miit.gov.cn"

module:
  mounts:
    - source: docs/content
      target: content
    - source: docs/data
      target: data
    - source: docs/layouts
      target: layouts
    - source: docs/assets
      target: assets
    - source: docs/static
      target: static
    - source: docs/i18n
      target: i18n
    - source: icons
      target: static/assets/icons
    - source: font
      target: static/assets/font
    - source: icons-list.json
      target: assets/icons-list.json

languages:
  zh:
    languageName: 中文
    weight: 1
    menu:
      main:
      - name: 安装
        url: /install/
        weight: 1
      - name: 使用
        url: /usage/
        weight: 2
      - name: 自定义
        url: /customize/
        weight: 3
  en:
    languageName: English
    weight: 2
    title: QWeather Icons
    description: Open source, beautiful weather icon library that supports SVG and Web Font, compatible with QWeather API, and also works in any project that needs weather icons. 
    qw: "https://www.qweather.com/en/"
    dev: "https://dev.qweather.com/en/"
    app: "https://www.qweather.com/en/app/"
    cc: "https://creativecommons.org/licenses/by/4.0/"
    menu:
      main:
      - name: Install
        url: /install/
        weight: 1
      - name: Usage
        url: /usage/
        weight: 2
      - name: Customize
        url: /customize/
        weight: 3



